const Reddit = require('reddit');

module.exports = {
	client: undefined,
	config: "",
	configData: "",
	spamCount: 1,
	spamUser: undefined,
	spamMessage: "",
	RAM: "",

	prefix: "dp --",
	color: 0xCC0000,
	help: "`help` - mostra a ajuda\n",
	configHelp: "",

	dpLinkExecuted: false,

	//wikiai: manager,
	markov: [
		"inicialmente os persas tinham criado um novo jogo",
		"mas depois de conseguirem todos os objetivos contra os jogadores do oriente e vencerem o jogo por massacre",
		"o que terminou com grande parte da população infectada com AIDS",
		"é o nome de um dos maiores contribuidores incompreendidos da história da Desciclopédia",
		"era uma cidade-estado da Grécia antiga",
		"é um aglomerado de empresas e propriedades de origem francesa",
		"com esse discurso, venceu seu inimigo",
		"um monstro que rouba o pão com mortadela",
		"de pouco valor, como a sua família e você próprio",
		"o roubo de balinha foi considerado crime pelos juízes",
		"\n\n==História==\n",
		"alertá-lo sobre a seriedade do assunto",
		"acabou com os cabarés e saunas gays da cidade",
		"se não fosse por aquele acontecimento terrível",
		"\n\n===Passado===\n",
		"pouco se sabe sobre suas origens",
		"dizem que não houve sobreviventes naquela noite",
		"principalmente na propaganda do Dollynho",
		"temida entre crianças e adultos",
		"estupro numa pessoa arrombada",
		"o escritor do artigo",
		"homicídio qualificado pela rixa de vizinhos",
		"vender armas ilegalmente",
		"queria assistir a Galinha Pintadinha",
		"crimes contra os vegetais",
		"fazer sexo selvagem em áreas preservadas",
		"é possível notar que a gente se importa mais com vegetais do que com animais",
		"a explicação da mesma era igual",
		"sua mãe era uma grande fã da bala Halls",
		"vaso sanitário moderno",
		"infelizmente nenhum aluno conseguiu chegar ao seu nível",
		"mas fala que se no futuro não estiver ocupado jogando truco",
		"quando ele viu o resultado, se apaixonou imediatamente",
		"porque senão estraga tudo",
		"até porque, <b>NINGUÉM LIGA PRA ESSA PORRA</b>",
		"porque é um inútil que não consegue arrumar nenhum emprego de verdade",
		"porque criei esse artigo",
		"a grande fraqueza das criaturas gays que o vão atacar",
		"é, por [[incrível]] que pareça",
		"sim, eu sei, é a [[fórmula]] do [[sucesso]]",
		"álbum do gênero [[Rap|das quebradas]]",
		"que querem fantasiar melhor no momento de [[sexo]] solitário",
		"Nesse aqui, ele [[Pleonasmo|se superou de vez]] usando diversas [[maracutaia]]s da música, como [[sample]]s, fazer umas [[referência]]s à músicas de seus álbuns anteriores (obrigado ao [[Capitão América]] por essa informação!) e usar [[Lata|latinhas]] de [[Skol]] como percussão para certas músicas",
		"fazendo apenas 15% da população judaica praticar Sexo Nasal",
		"e é tudo culpa da Wikipédia.",
		"Fisk, Fisk! Inglês e Espanhol é Fisk!",
		"não animais como pessoas que acham engraçado os memes do \"nego ney\", e sim animais",
		"são uns jogos [[baseado]]s no",
		"para você entender o nível de o quanto eles estão desesperados em além de já te deixar [[gordo]], [[Diabetes|diabético]] e ainda por cima caído na [[Sérgio Mallandro|Pegadinha do Mallandro]] por ter acreditado nos [[anúncio]]s que fazem um sandubão de quinta parecer gostoso pacas, eles ainda por cima querem te deixar com uma puta duma raiva por causa dos jogos.",
		"a prostituição nos animais é quase sempre em troca de alguma coisa",
		"mas não se engane! [[Autotune|Tem caroço nesse angu...]]",
		"ao mesmo tempo mostrar o que acontece na terra perdida do Acre",
		"Nossa, não sabia que [[Deus]] tinha [[Twitter]]! Bom, vou segui-lo, então.",
		"Para tentarem ganhar uma graninha em cima dos [[Otaku|otakinhos]] [[Fedor|fedegosos]], eles",
		"Em muitos anos grandes cientistas tentaram explicar o [[Acre]] ([[Stephen Hawking]], [[Albert Einstein]] e o [[Sílvio Santos]])",
		"Nossa cidade é a prova que o diabo existe",
		"e é um símbolo do movimento [[LGBT|Lésbicas, Gays, Bichas e Travecos]], ou [[LGBTQQICAPF2K+|LGBTexto]], para os íntimos.",
		"típicos seguidores do Hitler, segundo a Encyclopedia Dramatica que falam",
		"e não é possível descer o [[cacete]] no [[Burro]], ou seja, o [[IBAMA]] estava supervisionando a [[produção]] do jogo.",
		"Quanto mais o nazismo mata, menos o comunismo mata",
		"é um pequeno esconderijo escravidão ao norte de Pelagiad... ops, desculpa, artigo errado!",
		"por Kim Jong-Un, a nossa citação é",
		"os brinquedos de Kim Jong Un usam tecnologia de funções picantes",
		"é um [[EP]] (do [[Alienígena|alienês]]: [[LP]] [[Broxa|broxado]])",
		"para a infelicidade da indústria musical",
		"e fez muito sucesso nos [[Estados Unidos]], vendendo 4 cópias desde seu lançamento.",
		"que sobrenome é esse? Bateram a cabeça no teclado? hjnnnn",
		"o maluco parece meu dedão depois de bater na quina da mesa.",
		"passou dos limites do aceitável com essa peruca e roupa reedeecula!",
		"O BOLSONARO TEVE HEMORRAGIA NO CU",
		"por ser apoiador declarado do Governo de Jair Bolsonaro",
		"acredita que o Deus dos Memes Chuck Norris dá uma surra do Capitão Nascimento",
		"essa bosta... quero dizer, busto",
		"e isso é muito cringe.",
		"Quanta criatividade!",
		"Esse aí não vendeu nenhuma cópia, nem uma pirateada sequer!",
		"descoberto em 11 de setembro de 1900 e guaraná de rolha pelo Sistema Brasileiro de Televisão no Brasil.",
		"é isso daí que o nome diz, animais raros e de má fama que cagam pra dentro, só que literalmente",
		"é um instrumento musical criado por um bicha, no momento em que um vibrador dele estava furado.",
		"Nunca se deve chamar Chuck Norris de nerd em plena Idade da Pedra quando este estiver inventando a roda",
		"é um grupo caçador de vampiros e de fãs da saga Crepúsculo",
		"É uma musiquinha em que o Jô Lénu fala sobre sua vidinha... bom, eu acho que ele nunca ouviu falar de um diário então teve que ser numa música, mesmo",
		"serve como música de fundo para esses vídeos motivacionais genéricos do Facebook",
		"é um daqueles chefões opcionais filhos da puta",
		"para definir uma alma branca em forma de bola que sai do corpo de algum punheteiro quando o mesmo <s>ejacula</s> morre",
		"é basicamente uma academia tradicional onde homens malham pra pegar mulher",
		"só aparecia quando um punheteiro chegava ao extremo da masturbação",
		"(não sei quanto a série, afinal, aquela porcaria é tão ruim que nem perdi meu tempo assistindo)",
		"é um dos caras mais ricos, se não for o mais rico do Brasil.",
		"do tema de reflexão e debate entre os maiores filósofos da humanidade, desde a antiguidade até os tempos atuais",
		"aquela sua mestra tesuda, sonho de todo adolescente punheteiro",
		"apesar dessa cara de professor de português e nome pejorativamente sugestivo,",
		"quanto era primeiro ministro, o que até uma criança de 4 anos portadora de microcefalia e de síndrome de down conseguiria deduzir",
		"sofrer de microcefalia",
		"realizado na época dos dinossauros",
		"recebeu o voto de alguns poucos [[microcefalia|microcéfalos]]",
		"para os viados de plantão, não perca tempo",
		"uma grande cidade com vasta produção de mangas e habitadas por viados",
		"é um super-herói (embora poucos acreditem)",
		"conhecidos por sua ávida fome em devorar e destruir alvéolos pulmonares de mamíferos",
		"e em suas muitas horas vagas, estupra viados e interpreta o queridíssimo",
		"essa coroa <s>teu cu na minha rola</s>",
		"a Power Ranger mais gostosa de todas",
		"um dos irmãos da fada já brigou com o Padre Quemedo",
		"na pessoa de [[Padre Quevedo]] e de [[Inri Cristo]], vencendo a ambos em um confronto épico",
		"pinto verde",
		"racistas contra pessoas verdes, como o Piccolo",
    	"e não só isso, como ele comeu o cu de quem estava lendo",
    	"geral comprou esse bagulho ao ponto desse troço ficar famosão até com os fetos não desenvolvidos",
		"desde que foi criado o [[Dollynho]]",
		"fez pacto com o capeta",
		"Dollynho, que sem propagandas não vendia como antes",
		"como várias empresas fazem é criar um <s>puteiro</s> massacote para a marca",
		"\n\n==Ver também==\n"
	],

	commands: [
		'help'
	],
	
	settings: {
		welcomeMessages: true,
		dpLink: false,
		dpLinkTime: 90000
	},

	save: async function(t,msg) {
		const fs = require('fs');
		if ( t.charAt( 0 ) == '"' ) {
			fs.writeFile("./configs/" + msg.guild.id + ".json",t.replace("\"","{"),function() {});
		} else {
			fs.writeFile("./configs/" + msg.guild.id + ".json",t,function() {});
		}
	},

	accounts: {
		reddit: new Reddit({
  			username: 'DescicloBot',
  			password: process.env.REDDIT_PASS,
  			appId: process.env.REDDIT_APP_ID,
  			appSecret: process.env.REDDIT_SECRET,
  			userAgent: process.env.USER_AGENT
		}),

		firebaseConfig: {
    		apiKey: process.env.FIREBASE_API_KEY,
    		authDomain: process.env.FIREBASE_AUTH_DOMAIN,
    		projectId: process.env.FIREBASE_PROJECT_ID,
    		storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
    		messagingSenderId: process.env.FIREBASE_MS_ID,
    		appId: process.env.FIREBASE_APP_ID
		}
	}
}